on:
  push:
    branches:
      - master
jobs: 
    deploy: 
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2
          with:
            hugo-version: 'latest'
            extended: true
        - name: Build
          run: hugo --minify
        # 使用云开发 Github Action 部署
        - name: Deploy
          uses: cuiks/tcb-action@master
          with: 
            # 云开发的访问密钥 secretId 和 secretKey
            secretId: ${{secrets.SECRET_ID}}
            secretKey: ${{secrets.SECRET_KEY}}
            # 云开发的环境id
            envId: ${{secrets.ENV_ID}}
            localPath: public/
            cloudPath: /
