on:
  push:
    branches:
      - master
jobs: 
    deploy: 
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2
          with:
            hugo-version: 'latest'
            extended: true
        - name: Build
          run: hugo --minify
        # 使用云开发 Github Action 部署
        - name: Upload COS
          uses: zkqiang/tencent-cos-action@v0.1.0
          with:
            args: delete -r -f / && upload -r ./public/ /
            secret_id: ${{ secrets.SECRET_ID }}
            secret_key: ${{ secrets.SECRET_KEY }}
            bucket: ${{ secrets.BUCKET }}
            region: ap-beijing
